name: build-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter_server=2.6.0 # https://github.com/jupyter-server/jupyter_server/releases
  - pip
  - pip:
    - jupyterlite-core==0.1.0 # https://github.com/jupyterlite/jupyterlite/releases
    - jupyterlite-xeus-python==0.8.1 # https://github.com/jupyterlite/xeus-python-kernel/releases
