name: build-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter_server
  - pip
  - pip:
    - jupyterlite-core==0.1.0b20 # https://pypi.org/project/jupyterlite-core/0.1.0b19/#history
    - jupyterlite-xeus-python==0.7.0 # https://pypi.org/project/jupyterlite-xeus-python/#history
