name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - nodefaults
dependencies:
  - matplotlib:
    channels:
      - https://repo.mamba.pm/emscripten-forge
  - numpy
  - pandas
  - tqdm