name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge # check packages at https://beta.mamba.pm/channels
  - conda-forge
  - nodefaults
dependencies:
  # DATA SCIENCE
  - pandas
  - numpy
  # PLOTTING
  - matplotlib
  # BRIGHTWAY DEPENDENCIES (NOT PURE PYTHON)
  - https://repo.mamba.pm/emscripten-forge::peewee # required by Brightway
  - https://repo.mamba.pm/emscripten-forge::lxml # required by Brightway
  # BRIGHTWAY CORE
  - conda-forge::bw2io=0.8.8 # https://anaconda.org/conda-forge/bw2io/files
  - conda-forge::bw2data=3.6.6 # https://anaconda.org/conda-forge/bw2data/files
  - conda-forge::bw2calc=1.8.2 # https://anaconda.org/conda-forge/bw2calc/files