name: xeus-python-kernel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - matplotlib:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - numpy:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - pandas:
      channels:
        - https://repo.mamba.pm/emscripten-forge
  - tqdm:
      channels:
        - conda-forge